//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpotifyArtist
    {
        public SpotifyArtist()
        {
            this.Albums = new HashSet<Album>();
            this.Tracks = new HashSet<Track>();
        }
    
        public int SpotifyArtistID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ArtistName { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
