//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int TrackID { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public Nullable<int> SpotifyArtistID { get; set; }
        public string Link { get; set; }
        public string TrackName { get; set; }
        public string PreviewUrl { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual SpotifyArtist SpotifyArtist { get; set; }
    }
}
